# DS Automation Assignment

Using our prepared churn data from week 2:
- use pycaret to find an ML algorithm that performs best on the data
    - Choose a metric you think is best to use for finding the best model; by default, it is accuracy but it could be AUC, precision, recall, etc. The week 3 FTE has some information on these different metrics.
- save the model to disk
- create a Python script/file/module with a function that takes a pandas dataframe as an input and returns the probability of churn for each row in the dataframe
    - your Python file/function should print out the predictions for new data (new_churn_data.csv)
    - the true values for the new data are [1, 0, 0, 1, 0] if you're interested
- test your Python module and function with the new data, new_churn_data.csv
- write a short summary of the process and results at the end of this notebook
- upload this Jupyter Notebook and Python file to a Github repository, and turn in a link to the repository in the week 5 assignment dropbox

*Optional* challenges:
- return the probability of churn for each new prediction, and the percentile where that prediction is in the distribution of probability predictions from the training dataset (e.g. a high probability of churn like 0.78 might be at the 90th percentile)
- use other autoML packages, such as TPOT, H2O, MLBox, etc, and compare performance and features with pycaret
- create a class in your Python module to hold the functions that you created
- accept user input to specify a file using a tool such as Python's `input()` function, the `click` package for command-line arguments, or a GUI
- Use the unmodified churn data (new_unmodified_churn_data.csv) in your Python script. This will require adding the same preprocessing steps from week 2 since this data is like the original unmodified dataset from week 1.

In [1]:
import pandas as pd

df = pd.read_csv('data/prepped_churn_data_unmodified.csv', index_col='customerID')
df

,tenure,PhoneService,Contract,PaymentMethod,MonthlyCharges,TotalCharges,Churn
customerID,,,,,,,
7590-VHVEG,1,0,0,2,29.85,29.85,0
5575-GNVDE,34,1,1,3,56.95,1889.50,0
3668-QPYBK,2,1,0,3,53.85,108.15,1
7795-CFOCW,45,0,1,0,42.30,1840.75,0
9237-HQITU,2,1,0,2,70.70,151.65,1
...,...,...,...,...,...,...,...
6840-RESVB,24,1,1,3,84.80,1990.50,0
2234-XADUH,72,1,1,1,103.20,7362.90,0
4801-JZAZL,11,0,0,2,29.60,346.45,0
8361-LTMKD,4,1,0,3,74.40,306.60,1
3186-AJIEK,66,1,2,0,105.65,6844.50,0

In [ ]:
conda update -n base conda

In [ ]:
conda install -c conda-forge pycaret -y

In [2]:
from pycaret.classification import setup, compare_models, predict_model, save_model, load_model

In [10]:
automl = setup(df, target='Churn')

In [22]:
automl[3]

,tenure,MonthlyCharges,TotalCharges,PhoneService_1,Contract_0,Contract_1,Contract_2,PaymentMethod_0,PaymentMethod_1,PaymentMethod_2,PaymentMethod_3
customerID,,,,,,,,,,,
4018-KJYUY,22.0,20.150000,432.500000,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
0771-WLCLA,16.0,112.949997,1882.550049,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
0596-BQCEQ,62.0,100.150002,6283.299805,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
7503-ZGUZJ,1.0,84.650002,84.650002,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
3932-IJWDZ,45.0,103.650002,4747.850098,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
7032-LMBHI,37.0,64.650002,2347.850098,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
3926-YZVVX,41.0,50.049999,2029.050049,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
4324-AHJKS,5.0,55.799999,300.399994,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
8984-EYLLL,64.0,105.250000,6823.399902,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1480-IVEVR,35.0,81.599998,2815.250000,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0

In [24]:
automl = setup(df, target='Churn', preprocess=False, numeric_features=['Contract','PhoneService','PaymentMethod'])

In [25]:
automl[3]

,tenure,PhoneService,Contract,PaymentMethod,MonthlyCharges,TotalCharges
customerID,,,,,,
3466-WAESX,16.0,1.0,0.0,2.0,69.099998,1083.699951
5600-PDUJF,6.0,1.0,0.0,1.0,49.500000,312.700012
3251-YMVWZ,53.0,1.0,1.0,0.0,24.049999,1301.900024
6888-SBYAI,1.0,1.0,0.0,3.0,50.700001,50.700001
2378-YIZKA,68.0,1.0,2.0,1.0,85.000000,5607.750000
...,...,...,...,...,...,...
4393-RYCRE,44.0,1.0,1.0,2.0,106.050003,4510.799805
3955-JBZZM,20.0,1.0,0.0,2.0,78.800003,1641.300049
4835-YSJMR,39.0,1.0,2.0,0.0,49.799999,1971.150024
5214-CHIWJ,27.0,1.0,1.0,3.0,20.299999,595.049988
6651-RLGGM,67.0,1.0,2.0,3.0,26.299999,1688.900024

In [44]:
best_model = compare_models()

In [45]:
best_model

In [46]:
df.iloc[-2:-1].shape

(1, 7)

In [48]:
predict_model(best_model, df.iloc[-2:-1])

,tenure,PhoneService,Contract,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Label,Score
customerID,,,,,,,,,
8361-LTMKD,4,1,0,3,74.4,306.6,1,0,0.5163

In [51]:
save_model(best_model, 'CATBOOST')

Transformation Pipeline and Model Succesfully Saved

(Pipeline(memory=None,
          steps=[('dtypes',
                  DataTypes_Auto_infer(categorical_features=[],
                                       display_types=True, features_todrop=[],
                                       id_columns=[],
                                       ml_usecase='classification',
                                       numerical_features=['Contract',
                                                           'PhoneService',
                                                           'PaymentMethod'],
                                       target='Churn', time_features=[])),
                 ['trained_model',
                  <catboost.core.CatBoostClassifier object at 0x7fda3a47bc40>]],
          verbose=False),
 'CATBOOST.pkl')

In [52]:
import pickle

with open('CATBOOST_model.pk', 'wb') as f:
    pickle.dump(best_model, f)

In [53]:
with open('CATBOOST_model.pk', 'rb') as f:
    loaded_model = pickle.load(f)

In [54]:
new_data = df.iloc[-2:-1].copy()
new_data.drop('Churn', axis=1, inplace=True)
loaded_model.predict(new_data)

array([0])

In [55]:
loaded_lda = load_model('CATBOOST')

Transformation Pipeline and Model Successfully Loaded

In [56]:
predict_model(loaded_lda, new_data)

,tenure,PhoneService,Contract,PaymentMethod,MonthlyCharges,TotalCharges,Label,Score
customerID,,,,,,,,
8361-LTMKD,4,1,0,3,74.4,306.6,0,0.5163

In [57]:
pip install ipython

Requirement already satisfied: ipython in /opt/anaconda3/lib/python3.9/site-packages (8.3.0)
Requirement already satisfied: jedi>=0.16 in /opt/anaconda3/lib/python3.9/site-packages (from ipython) (0.18.1)
Requirement already satisfied: matplotlib-inline in /opt/anaconda3/lib/python3.9/site-packages (from ipython) (0.1.2)
Requirement already satisfied: pexpect>4.3 in /opt/anaconda3/lib/python3.9/site-packages (from ipython) (4.8.0)
Requirement already satisfied: stack-data in /opt/anaconda3/lib/python3.9/site-packages (from ipython) (0.2.0)
Requirement already satisfied: backcall in /opt/anaconda3/lib/python3.9/site-packages (from ipython) (0.2.0)
Requirement already satisfied: setuptools>=18.5 in /opt/anaconda3/lib/python3.9/site-packages (from ipython) (61.2.0)
Requirement already satisfied: pickleshare in /opt/anaconda3/lib/python3.9/site-packages (from ipython) (0.7.5)
Requirement already satisfied: traitlets>=5 in /opt/anaconda3/lib/python3.9/site-packages (from ipython) (5.1.1)
Requirement already satisfied: appnope in /opt/anaconda3/lib/python3.9/site-packages (from ipython) (0.1.2)
Requirement already satisfied: decorator in /opt/anaconda3/lib/python3.9/site-packages (from ipython) (5.1.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /opt/anaconda3/lib/python3.9/site-packages (from ipython) (3.0.20)
Requirement already satisfied: pygments>=2.4.0 in /opt/anaconda3/lib/python3.9/site-packages (from ipython) (2.11.2)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /opt/anaconda3/lib/python3.9/site-packages (from jedi>=0.16->ipython) (0.8.3)
Requirement already satisfied: ptyprocess>=0.5 in /opt/anaconda3/lib/python3.9/site-packages (from pexpect>4.3->ipython) (0.7.0)
Requirement already satisfied: wcwidth in /opt/anaconda3/lib/python3.9/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython) (0.2.5)
Requirement already satisfied: executing in /opt/anaconda3/lib/python3.9/site-packages (from stack-data->ipython) (0.8.3)
Requirement already satisfied: pure-eval in /opt/anaconda3/lib/python3.9/site-packages (from stack-data->ipython) (0.2.2)
Requirement already satisfied: asttokens in /opt/anaconda3/lib/python3.9/site-packages (from stack-data->ipython) (2.0.5)
Requirement already satisfied: six in /opt/anaconda3/lib/python3.9/site-packages (from asttokens->stack-data->ipython) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [58]:
from IPython.display import Code

Code('predict_churn.py')

import pandas as pd
from pycaret.classification import predict_model, load_model

def load_data(filepath):
    """
    Loads churn data into a DataFrame from a string filepath.
    """
    df1 = pd.read_csv(filepath, index_col='customerID')
    return df1


def make_predictions(df1):
    """
    Uses the pycaret best model to make predictions on data in the df dataframe.
    """
    model = load_model('GBC')
    predictions = predict_model(model, data=df1)
    predictions.rename({'Label': 'Churn_prediction'}, axis=1, inplace=True)
    predictions['Churn_prediction'].replace({1: 'Churn', 0: 'No Churn'},
                                            inplace=True)
    return predictions['Churn_prediction']


if __name__ == "__main__":
    df1 = load_data('data/new_churn_data_unmodified.csv')
    predictions = make_predictions(df1)
    print('predictions:')
    print(predictions)

In [62]:
%run predict_churn.py

Transformation Pipeline and Model Successfully Loaded
predictions:
customerID
9305-CKSKC       Churn
1452-KNGVK    No Churn
6723-OKKJM    No Churn
7832-POPKP    No Churn
6348-TACGU    No Churn
Name: Churn_prediction, dtype: object

# Summary

Write a short summary of the process and results here.